name: Deploy Next JS Ap

on: 
  push:
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest

    concurrency:
      group: deploy
      cancel-in-progress: true

    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
          
      - name: Install Dependencies
        run: npm install

      - name: Run dev server
        run: npm run dev

      - name: Deploy
        run: echo "Deploy your application"
